#!/bin/sh
set -e

[ ! -n "$HOME" ] && exit 1;

ln -sf ~/.zsh.d/zlogin ~/.zlogin
ln -sf ~/.zsh.d/zlogout ~/.zlogout

echo 'source ~/.zsh.d/zshenv' >> $HOME/.zshenv

cat <<'EOF' > $HOME/.zshrc
source ~/.zsh.d/01zshrc
source ~/.zsh.d/10functions.zsh
source ~/.zsh.d/20theme.zsh
if exists peco; then
    source ~/.zsh.d/peco.zsh
fi
source ~/.zsh.d/aliases.zsh
source ~/.zsh.d/packages.zsh
if exists direnv; then
    eval "$(direnv hook zsh)"
fi
EOF

ls -hal ~/.zsh{.d,env,rc} ~/.zlog{in,out}

cat <<'EOF'

,--.                       
,-|  | ,---. ,--,--,  ,---.  
' .-. || .-. ||      \| .-. : 
\ `-' |' '-' '|  ||  |\   --. 
`---'  `---' `--''--' `----' 

EOF
